#
###################################
# Site wide configuration
####################################
#
title: Sherl Fang
email: sherlfang@gmail.com
description: Keep calm and carry on.
url: "http://www.iamsherl.com"


#
###################################
# Jekyll configuration
####################################
#
timezone:          China
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Sherl Fang
  avatar: leonids-logo.png
  job: "UX Designer"
  bio: "主线IxD,辅线产品与编程的UXer"
  email: sherlfang@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: sherlfang
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
